remote_theme: pages-themes/minimal@v0.2.0
title: Thoreau Society Annual Gathering 2024
description: "Wednesday, July 10, 1&ndash;3:30 p.m., Trinity Episcopal Church, Main Hall. You'll get the most out of this workshop if you bring a laptop computer."
logo: "/images/maxham_blue_150x150.png"